### PR TITLE
CRUD Entities Ticket_Type

### PR DESCRIPTION
**Pull request by nguyenthanhdat1997**

### CODE REVIEW

**Review by NhanTran262 — APPROVED** [review]
Well done

**Review by thinhphan8 — APPROVED** [review]
Approved!

**Review by baoandlk93 — CHANGES_REQUESTED** [review]
delete 2 file redundant

**Review by nguyenthanhdat1997 — COMMENTED** [review]
Nice!

**Review by baoandlk93 — APPROVED** [review]

**Pull request merged**
